general.import = [
  "~/.config/alacritty/themes/themes/nord.toml"
]

# [terminal.shell]
# program = "/run/current-system/sw/bin/tmux" # <- Set your path
# args = ["new-session", "-A", "-D", "-s", "main"]

[font]
size = 12.0
normal = { family = "JetBrainsMono Nerd Font", style = "Regular"}

[window]
startup_mode = "Maximized"
opacity = 0.95
blur = true

# Allow move cursor word by word for tmux with zsh
[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF"},
  { key = "Left",  mods = "Alt", chars = "\u001BB"},
  { key = "V", mods = "Command|Shift", action = "Paste" },
]
